name: Build and release 24.10-nss and 24.10-nss-custom for Linksys MX5300

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex gawk \
            gcc-multilib git make ncurses-dev libssl-dev \
            unzip wget rsync

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        
      - name: Set defconfig
        run: make defconfig V=s

      - name: Download sources
        run: make download -j$(nproc) V=s

      - name: Build firmware
        run:  make -j$(nproc) V=s
      
      - name: Rename firmware
        run: |
          mv bin/targets/qualcommax/ipq807x/openwrt-*-factory.bin bin/targets/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-factory.bin
          mv bin/targets/qualcommax/ipq807x/openwrt-*-sysupgrade.bin bin/targets/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-sysupgrade.bin
  
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-nss-mx5300
          path: bin/targets/
          retention-days: 1
  build-custom:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          ref: 24.10-nss-custom

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex gawk \
            gcc-multilib git make ncurses-dev libssl-dev \
            unzip wget rsync

      - name: Secure .config
        run: cp .config .config.backup

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Restore .config
        run: mv .config.backup .config

      - name: Make oldconfig
        run: yes "" | make oldconfig

      - name: Download sources
        run: make download -j$(nproc)

      - name: Build firmware
        run:  make -j$(nproc) V=s

      - name: Rename firmware
        run: |
          mv bin/targets/qualcommax/ipq807x/openwrt-*-factory.bin bin/targets/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-custom-factory.bin
          mv bin/targets/qualcommax/ipq807x/openwrt-*-sysupgrade.bin bin/targets/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-custom-sysupgrade.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-nss-mx5300-custom
          path: bin/targets/
          retention-days: 1

  release:
    needs: [build, build-custom]
    runs-on: ubuntu-latest
    steps:
        - name: Download build
          uses: actions/download-artifact@v4
          with:
            name: openwrt-nss-mx5300
            path: release-files

        - name: Download custom build
          uses: actions/download-artifact@v4
          with:
            name: openwrt-nss-mx5300-custom
            path: release-files-custom
        
        - name: Set release tag and name
          run: |
            RELEASE_DATE=$(date +'%Y%m%d')
            RELEASE_TAG="24.10-nss-nightly-${RELEASE_DATE}"
            echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
            echo "Release Name: ${RELEASE_TAG}"

        - name: Generate sha256sums
          run: |
            sha256sum release-files-custom/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-custom-factory.bin \
                      release-files-custom/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-custom-sysupgrade.bin \
                      release-files/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-factory.bin \
                      release-files/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-sysupgrade.bin > release-files/qualcommax/ipq807x/sha256sums.txt
                      

        - name: Update release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ env.RELEASE_TAG }}
            name: ${{ env.RELEASE_TAG }}
            files: |
              release-files-custom/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-custom-factory.bin
              release-files-custom/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-custom-sysupgrade.bin
              release-files/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-factory.bin
              release-files/qualcommax/ipq807x/openwrt-nss-24.10-mx5300-sysupgrade.bin
              release-files/qualcommax/ipq807x/sha256sums.txt

